fix-uploaded-image-size in create create coin form
dcts/radix.meme pull request #150
Opened 2024-09-29 20:31 UTC by SiegfriedBz

<img width="518" alt="Screenshot 2024-09-29 at 22 30 52" src="https://github.com/user-attachments/assets/b95ee623-7087-4ef0-bac2-7e8b46b4b202">

2024-09-29 21:01 UTC, dcts requested changes
Please resolve the 2 comments and I'll happily merge.

2024-09-30 01:27 UTC, dcts commented
Also this issue is related, in case you want to tackle it (please assign yourself if you decide to do it):
https://github.com/dcts/radix.meme/issues/152

2024-10-01 17:32 UTC, SiegfriedBz commented on components/CreateCoinForm.tsx
> -                  style={{ width: "auto", height: "auto" }}
I can t reproduce this error, can you please tell me what was error ?

2024-10-01 18:17 UTC, SiegfriedBz commented on components/CreateCoinForm.tsx
> -                  style={{ width: "auto", height: "auto" }}
I added 
style={{ width: "144px", height: "144px" }}
and not 
style={{ width: "auto", height: "auto" }}
as it was overwriting the w/h I m setting 
width={144}
height={144}

but I couldn t reproduce any error when removing style={{ width: "XXX", height: "XXX" }}

2024-10-01 21:09 UTC, dcts commented on components/CreateCoinForm.tsx
> -                  style={{ width: "auto", height: "auto" }}
I think the issue arises only if we dont set it, if its explicitly set this should work. Will merge and in case it doesnt work I'll create another PR with a fix.

2024-10-01 21:10 UTC, dcts approved these changes
Looks good!

2024-10-01 21:10 UTC, merged